#!/usr/bin/env node
/**
 * Combines the Apps Script files in src/ into a single file, dist/TravelBlocks.gs,
 * so you only have to paste that one file (plus your optional Config.local.gs)
 * into your Apps Script project.
 *
 * Usage: node scripts/build.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
// Code.gs first, so syncTravel is the first function (the one Apps Script runs by default).
// Config.local.gs is left out on purpose: it is personal.
const SOURCE_FILES = ['Code.gs', 'Config.gs', 'Routes.gs', 'NsApi.gs'];
const OUT_FILE = path.join(ROOT, 'dist', 'TravelBlocks.gs');

const header = [
  '/**',
  ' * Auto Schedule Travel Time: https://github.com/StijnRis/auto-schedule-travel-time',
  ` * Generated by scripts/build.js from src/${SOURCE_FILES.join(', src/')}. Do not edit;`,
  ' * put your own settings in a separate Config.local file or in Script Properties.',
  ' */',
  ''
].join('\n');

const parts = SOURCE_FILES.map(name => {
  const code = fs.readFileSync(path.join(ROOT, 'src', name), 'utf8').replace(/\r\n/g, '\n').trimEnd();
  return `// ===== ${name} =====\n\n${code}\n`;
});

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, header + '\n' + parts.join('\n'));
console.log(`Wrote ${path.relative(ROOT, OUT_FILE)}`);
